### ISSUE TITLE
Update Ansible Galaxy to recognize new changes.

### ISSUE THREAD

**Issue by adamzimmermann** [ChromaticHQ/ansible-deploy-drupal#31]
## Description

https://galaxy.ansible.com/ChromaticHQ/deploy-drupal

<img width="663" alt="Screen Shot 2020-10-06 at 4 05 14 PM" src="https://user-images.githubusercontent.com/1349906/95260090-c9d8bc00-07ed-11eb-89b5-beb90c5ae707.png">

This isn't reflecting our recent work. It would be great to get our quality score up too.

## Proposed Solution

I'm not sure what we need to do, but wanted to document it.

## Alternatives Considered

TK?

## Additional Context

Making sure we have things cleaned up in preparation for my blog post.

- https://github.com/ChromaticHQ/Blog-Posts/issues/356

**Comment by markdorison** [comment]
There might have been an easier way to do this but Galaxy is very unintuitive. I believe things broke when we changed the default branch name to `main`. I deleted the role from galaxy and re-added it: https://galaxy.ansible.com/ChromaticHQ/deploy_drupal

**Comment by adamzimmermann** [comment]
@markdorison thank you. 🙏
