### ISSUE TITLE
Add ansible.cfg file to role

### ISSUE THREAD

**Issue by ctorgalson** [ChromaticHQ/ansible-deploy-drupal#6]
Normally we'd rely on the caller's environment to provide and `ansible.cfg` file. But since we want to use this role to reduce the amount of code duplication in projects that have little or no other ansible content, we could provide a basic one here (note: cows included by default if `cowsay` is present):

```ini
[defaults]
stdout_callback = yaml
[ssh_connection]
pipelining = True
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
```

The script in various repos could use this file like this:

```
ANSIBLE_CONFIG="/path/to/roles/ansible-deploy-drupal/ansible.cfg" ansible-playbook ...
```

To _not_ use the file the calling script would only have to _not_ set the env var (or set it to another file).

**Comment by adamzimmermann** [comment]
Is this something we still think is valuable or should we close this?
