### ISSUE TITLE
Variable-ize settings file name

### ISSUE THREAD

**Issue by ctorgalson** [ChromaticHQ/ansible-deploy-drupal#9]
We alter permissions on `sites/{{ deploy_drupal_sitename }}` and `sites/{{ deploy_drupal_sitename }}/settings.php`.

Given that it's common to use e.g. `settings.local.php` and `settings.environment.php`, we should make the file name variable. The variable should contain the current value so that existing implementations don't need to change.

**Comment by adamzimmermann** [comment]
Should we really be doing this for all `settings.*.php` files? Perhaps we should leverage a pattern? I'm guessing Ansible has some mechanism for handling that?

cc @markdorison

**Comment by ctorgalson** [comment]
@adamzimmermann I can't remember if something in particular made me suggest this :roll_eyes:, or if it was only that `settings.php` is one of the few hardcoded strings that _might_ not apply in every possible use of the role.

I'm also not positive that I get what you mean by  "pattern," but the role only ever runs in one directory, so providing a single variable should be ok (also, we can use group_vars to override defaults on a per-host/group basis).

**Comment by adamzimmermann** [comment]
@ctorgalson for example:

```
ls -la
total 96
dr-xr-xr-x 3 root     root   226 Sep  8 13:07 .
drwxr-xr-x 3 root     root   130 Sep  8 13:07 ..
-rw-r--r-- 1 root     root  6762 Sep  8 13:07 default.services.yml
-rw-r--r-- 1 root     root 31870 Sep  8 13:07 default.settings.php
drwxrwx--- 7 www-data root   260 Sep 21 19:40 files
-rw-r--r-- 1 root     root  5560 Sep  8 13:04 services.yml
-rw-r--r-- 1 root     root  1857 Sep  8 13:04 settings.lando.php
-r--r--r-- 1 root     root 27847 Sep  8 13:04 settings.php
-rw-r--r-- 1 root     root  6237 Sep  8 13:04 settings.platformsh.php
-rw-r--r-- 1 root     root  2080 Sep  8 13:04 settings.redis.php
-rw-r--r-- 1 root     root  1038 Sep  8 13:04 settings.tugboat.php
```

We have `settings.php` locked down fully, but we really want to lock down all of the files with the name `settings.*.php`, right?

**Comment by adamzimmermann** [comment]
@ctorgalson perhaps my [draft PR](https://github.com/ChromaticHQ/ansible-deploy-drupal/pull/29/files) will explain it better?
